version: "3.8"

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: amprahan_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: amprahan
      MYSQL_USER: amprahan_user
      MYSQL_PASSWORD: amprahan_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - amprahan_network

  # PHP Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: amprahan_backend
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: amprahan
      DB_USER: amprahan_user
      DB_PASS: amprahan_pass
    networks:
      - amprahan_network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: amprahan_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      REACT_APP_API_URL: http://localhost:8000
    depends_on:
      - backend
    networks:
      - amprahan_network

volumes:
  mysql_data:

networks:
  amprahan_network:
    driver: bridge
